version: "3.8"

services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /workspace
        volumes:
            - type: bind
              source: ..
              target: /workspace
              consistency: cached
            # windowを出すためのソケットファイルマウント
            - type: bind
              source: /tmp/.X11-unix/X0
              target: /tmp/.X11-unix/X0
            # gpuのデバイスファイルマウント
            - type: bind
              source: /dev/dri/card0
              target: /dev/dri/card0
        command: /bin/sh -c "while sleep 1000; do :; done" # devcontainerで起動させるために必要
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 - capabilities: [gpu]
