version: "3.8"

services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /workspace
        volumes:
            - type: bind
              source: ..
              target: /workspace
              consistency: cached
            # ubuntuのみ設定
            - type: bind
              source: /tmp/.X11-unix/X0
              target: /tmp/.X11-unix/X0
        environment:
            - DISPLAY=$CONTAINER_DISPLAY
        command: /bin/sh -c "while sleep 1000; do :; done" # devcontainerで起動させるために必要
